# Data referencing
MATRIX_FILENAME = "garden_matrix.xlsx"
PLANT_NAME_COLUMN = "Plant"
FRIEND_COLUMN = "Friend"
FRIEND_VALUE = FRIEND_COLUMN.upper()
FOE_COLUMN = "Foe"
FOE_VALUE = FOE_COLUMN.upper()
NEUTRAL_VALUE = ""

# Weights
FRIEND_WEIGHT = 1
NEUTRAL_WEIGHT = 2
BLANK_WEIGHT = 3
FOE_WEIGHT = 4

# Formatting
BLANK_PREFIX = "BLANK_"

# Parameters
NEIGHBOR_LIMITS = 2